[project]
name = "pythontraininghall"
version = "0.1.0"
description = "Python训练馆，练习Python技能"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "opencv-python>=4.11.0.86",
    "wxpython>=4.2.3",
]
